name: lx/lx-doc

autoload:
  psr-4:
    lx\doc\: ''

service:
  class: lx\doc\Service

  router:
    type: map
    routes:
      parser: {plugin: docParser}

  plugins: plugin
  models: model
  modelCrudAdapter: \lx\DbCrudAdapter
